name: Build APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Show files
        run: ls -la
      - uses: actions/upload-artifact@v3
        with:
          name: milord-app
          path: index.html
